import 'package:myapp/models/event.dart';

class EventStatistics {
  final String id;
  final String eventId;
  final String eventTitle;
  final String userId;
  final DateTime date;
  final bool wasCompleted;
  final DateTime scheduledStartTime;
  final DateTime? scheduledEndTime;
  final DateTime? completedTime;
  final String category;
  final int? importance;
  final Duration? completionDuration;
  final DateTime createdAt;

  EventStatistics({
    required this.id,
    required this.eventId,
    required this.eventTitle,
    required this.userId,
    required this.date,
    required this.wasCompleted,
    required this.scheduledStartTime,
    this.scheduledEndTime,
    this.completedTime,
    required this.category,
    this.importance,
    this.completionDuration,
    required this.createdAt,
  });

  factory EventStatistics.fromEvent(Event event, bool wasCompleted, [DateTime? completedTime]) {
    final date = DateTime(event.startTime.year, event.startTime.month, event.startTime.day);
    
    return EventStatistics(
      id: '', // Will be generated by database
      eventId: event.id,
      eventTitle: event.title,
      userId: event.userId,
      date: date,
      wasCompleted: wasCompleted,
      scheduledStartTime: event.startTime,
      scheduledEndTime: event.endTime,
      completedTime: completedTime,
      category: event.category,
      importance: event.importance,
      completionDuration: null, // Will be calculated by database trigger
      createdAt: DateTime.now(),
    );
  }

  factory EventStatistics.fromJson(Map<String, dynamic> json) {
    return EventStatistics(
      id: json['id'],
      eventId: json['event_id'],
      eventTitle: json['event_title'],
      userId: json['user_id'],
      date: DateTime.parse(json['date']),
      wasCompleted: json['was_completed'],
      scheduledStartTime: DateTime.parse(json['scheduled_start_time']),
      scheduledEndTime: json['scheduled_end_time'] != null 
          ? DateTime.parse(json['scheduled_end_time']) 
          : null,
      completedTime: json['completed_time'] != null 
          ? DateTime.parse(json['completed_time']) 
          : null,
      category: json['category'],
      importance: json['importance'],
      completionDuration: json['completion_duration'] != null 
          ? _parseDuration(json['completion_duration'])
          : null,
      createdAt: DateTime.parse(json['created_at']),
    );
  }

  static Duration? _parseDuration(String? durationString) {
    if (durationString == null) return null;
    
    // PostgreSQL interval format: "HH:MM:SS" or "X days HH:MM:SS"
    final parts = durationString.split(':');
    if (parts.length >= 3) {
      final hours = int.tryParse(parts[0]) ?? 0;
      final minutes = int.tryParse(parts[1]) ?? 0;
      final seconds = int.tryParse(parts[2].split('.')[0]) ?? 0;
      return Duration(hours: hours, minutes: minutes, seconds: seconds);
    }
    
    return null;
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id.isEmpty ? null : id,
      'event_id': eventId,
      'event_title': eventTitle,
      'user_id': userId,
      'date': date.toIso8601String().split('T')[0], // Date only
      'was_completed': wasCompleted,
      'scheduled_start_time': scheduledStartTime.toIso8601String(),
      'scheduled_end_time': scheduledEndTime?.toIso8601String(),
      'completed_time': completedTime?.toIso8601String(),
      'category': category,
      'importance': importance,
      'created_at': createdAt.toIso8601String(),
    };
  }
}
